# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
    ],
    hiddenimports=[
        'paramiko',
        'paramiko.transport',
        'paramiko.sftp_client',
        'paramiko.sftp_handle',
        'paramiko.sftp_server',
        'paramiko.server',
        'paramiko.channel',
        'paramiko.auth_handler',
        'paramiko.agent',
        'paramiko.common',
        'paramiko.compress',
        'paramiko.config',
        'paramiko.dsskey',
        'paramiko.ecdsakey',
        'paramiko.ed25519key',
        'paramiko.file',
        'paramiko.hostkeys',
        'paramiko.kex_curve25519',
        'paramiko.kex_ecdh_nist',
        'paramiko.kex_gex',
        'paramiko.kex_group1',
        'paramiko.kex_group14',
        'paramiko.kex_group16',
        'paramiko.message',
        'paramiko.packet',
        'paramiko.pipe',
        'paramiko.pkey',
        'paramiko.proxy',
        'paramiko.rsakey',
        'paramiko.sftp_attr',
        'paramiko.ssh_exception',
        'paramiko.util',
        'paramiko.win_pageant',
        'cryptography',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        'python_dotenv',
        'dotenv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='EC2Dashboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
)
